version: 2.1

orbs:
  loom-docker: loomhq/docker@1.0.2

workflows:
  version: 2
  build:
    jobs:
      # Build only
      - loom-docker/build-image:
          context: aws
          image-name: veneur
          dockerfile: public-docker-images/Dockerfile-debian-sid
          filters:
            branches:
              ignore: master

      # Publish
      - loom-docker/build-and-push-image:
          context: aws
          image-name: veneur
          dockerfile: public-docker-images/Dockerfile-debian-sid
          filters:
            branches:
              only: master
